<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>JohnLudlow.GameEngineAdapter.Benchmarks</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameEngineAdapter.Core\GameEngineAdapter.Core.csproj" />
  </ItemGroup>

</Project>
